version: '3.8'

services:
  backend:
    build:
      context: ./backend/ChatApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_GPT_NAME=${AZURE_OPENAI_GPT_NAME}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}

  frontend:
    build:
      context: ./frontend/ChatClient
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
